### ISSUE TITLE
would you add an open source license and push to Nuget

### ISSUE THREAD

**Issue by Sohojoe** [ninjastacktech/opensea-net#1]
Hi, there is no good OpenSea lib on nuget and you codes is the best. Would you be interested in adding an open source license (like MIT) and pushing to nuget so it is easier to use?

**Comment by cristipufu** [comment]
Hello there!
Yes, I will do that today

**Comment by cristipufu** [comment]
https://www.nuget.org/packages/OpenSeaClient/ 🎉
