### ISSUE TITLE
[bug] Get forbidden error when no api key

### ISSUE THREAD

**Issue by Sohojoe** [ninjastacktech/opensea-net#3]
OpenSea is throwing a forbidden error.  Your code is checking if ApiKey is null or empty and no longer sends the empty apikey to opensea. See fix in #2

**Comment by cristipufu** [comment]
Well there are some endpoints that require an API Key -which one did you test?

**Comment by cristipufu** [comment]
Yes, it seems like some endpoints just need the header - pushed new version https://www.nuget.org/packages/OpenSeaClient/1.0.3
